"""Fix unit is_active to boolean

Revision ID: 062043a7cd99
Revises: None
Create Date: 2026-01-21 09:13:40.078155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062043a7cd99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This logic handles "active" -> True and everything else -> False
    op.alter_column('units', 'is_active',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               postgresql_using="""
               CASE 
                   WHEN is_active = 'active' THEN true 
                   WHEN is_active = 'true' THEN true 
                   WHEN is_active = '1' THEN true 
                   ELSE false 
               END
               """,
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###